# Generated by Django 4.0.4 on 2022-11-03 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Elementos1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Year', models.CharField(max_length=100, null=True)),
                ('Cantidad', models.PositiveIntegerField(null=True)),
                ('Categoria', models.CharField(choices=[('Cesarea', 'Cesarea'), ('Parto natural', 'Parto natural')], max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Elementos2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Year', models.CharField(max_length=100, null=True)),
                ('Cantidad', models.PositiveIntegerField(null=True)),
                ('Categoria', models.CharField(choices=[('Cesarea', 'Cesarea'), ('Parto natural', 'Parto natural')], max_length=50, null=True)),
            ],
        ),
    ]
